name: widget-server-devops-pipeline
services:
  
  db:
    image: postgres:latest
    container_name: widget-server-db-devops
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: widget-server
    volumes:
      - db-data:/var/lib/postgresql/data # Persist data in a named volume

  app:
    build: .
    container_name: widget-server-app-devops
    ports:
      - 3000:3333 # Expose port 3333 from the container to port 3000 on the host
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=#
      - CLOUDFLARE_SECRET_ACCESS_KEY=#
      - CLOUDFLARE_BUCKET=#
      - CLOUDFLARE_ACCOUNT_ID=#
      - CLOUDFLARE_PUBLIC_URL=http://localhost:3000

volumes:
  db-data: